const EVENTS = [
    {
        id: 'double_work',
        name: 'Double Work Payouts',
        description: 'All /work payouts are doubled for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '💼',
        color: 0x00cc44,
    },
    {
        id: 'double_daily',
        name: 'Double Daily Rewards',
        description: 'Daily rewards are doubled for the next 24 hours.',
        duration: 24 * 60 * 60 * 1000,
        emoji: '🎁',
        color: 0xFFD700,
    },
    {
        id: 'crime_boost',
        name: 'Crime Wave',
        description: 'Crime success rates are boosted by 20% for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '🔪',
        color: 0xff3333,
    },
    {
        id: 'rob_boost',
        name: 'Open Season',
        description: 'Rob success rates are boosted by 25% for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '🥷',
        color: 0xff3333,
    },
    {
        id: 'gambling_boost',
        name: 'Hot Table',
        description: 'All gambling payouts have a 10% bonus for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '🎰',
        color: 0xFFD700,
    },
    {
        id: 'fishing_boost',
        name: 'Feeding Frenzy',
        description: 'Fish catch rates shift toward rarer tiers for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '🎣',
        color: 0x60a5fa,
    },
    {
        id: 'mining_boost',
        name: 'Rich Vein',
        description: 'Mining ore values are doubled for 30 minutes.',
        duration: 30 * 60 * 1000,
        emoji: '⛏️',
        color: 0x60a5fa,
    },
    {
        id: 'tax_holiday',
        name: 'Tax Holiday',
        description: 'All server taxes are waived for 1 hour.',
        duration: 60 * 60 * 1000,
        emoji: '🏦',
        color: 0x00cc44,
    },
    {
        id: 'stock_surge',
        name: 'Market Surge',
        description: 'All stocks tick upward by 5-15% immediately.',
        duration: 0,
        emoji: '📈',
        color: 0x00cc44,
        instant: true,
    },
    {
        id: 'stock_crash',
        name: 'Market Crash',
        description: 'All stocks drop by 10-25% immediately.',
        duration: 0,
        emoji: '📉',
        color: 0xff3333,
        instant: true,
    },
];

module.exports = EVENTS;
